# Site
repository: erenovic/cetineren # Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Eren Cetin
title: Undergraduate Research Assistant
email: ecetin17 [at] ku.edu.tr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  erenovic
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: erencetinn
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0000-0000-0000
googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Link name
  icon: fas fa-file
  url: https://docs.google.com/viewerng/viewer?url=https://github.com/erenovic/cetineren/raw/master/assets/Cetin-Eren-Resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a senior in Electrical & Electronics Engineering with a double major in Economics at Koç University. 
  My professional interests are in <mark>machine learning</mark>, <mark>image/video processing</mark>, <mark>computer vision</mark>, 
  and <mark>optimization</mark>.
  <br><br><br>
  For most of my research and education, I had my hands dirty on frameworks, languages and tools such as <mark>Python</mark>, 
  <mark>MATLAB</mark>, <mark>PyTorch</mark>, <mark>C/C++</mark>, <mark>Slurm</mark> and <mark>LaTeX</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Learned Bidirectional Video Compression Framework
        link: https://drive.google.com/file/d/1EPeK4Fpj-0r8shqzkSkJuaVayt2f4GvD/view?usp=sharing
        link_text: Thesis Paper
        additional_links:
          - title:  Github page
            icon: fab fa-github
            url: https://github.com/erenovic/Bidirectional-Video-Compression-with-Motion-Refinement
        quote: >
          Flexible-Rate Bidirectional Video Compression with Motion Refinement
        description: | # this will include new lines to allow paragraphs
          Built a learned hierarchical bidirectional video compression model that utilizes 
          motion predictions and allows achievement of multiple rate-distortion tradeoffs 
          using single motion compression network with varying intra-frame coding networks.
  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: KUIS AI Lab
        sub_title: Undergraduate Research under Professor Murat Tekalp
        caption: 06.2020 - present
        link: http://home.ku.edu.tr/~mtekalp/
        quote: >
          Research interests of Professor Tekalp captures a wide range of image/video processing applications including 
          image/video super resolution, compression and restoration. With his vast research experience, Professor Tekalp helped me
          broaden my knowledge on above mentioned tasks and guided me through our research.
        description: | # this will include new lines to allow paragraphs
          During my undergraduate research, I have worked on image and video compression using recurrent and fully convolutional variational 
          auto-encoders. My projects included our work on the design of a novel bidirectional frame compression network and 
          several implementation of recent works in the literature using PyTorch machine learning framework.
      - layout: left
        title: KUSRP
        sub_title: Summer Research under Professor Aykut Erdem
        caption: 06.2021 - 09.2021
        link: https://aykuterdem.github.io/
        quote: >
          Professor Erdem conducts research on a diverse set of topics, ranging from image editing to visual saliency estimation, 
          and to multimodal learning for integrated vision and language.
        description: | # this will include new lines to allow paragraphs
          During my time at Koç University Summer Research Program (KUSRP), I studied style transfer and image manipulation with generative
          adversarial networks. Worked on implementation of “Swapping Autoencoder for Deep Image Manipulation” by Park et al. (2020).
  - title: Education
    layout: list
    content:
      - layout: left
        title: Koç University
        sub_title: BSc Electrical & Electronics Engineering
        caption: 2017 - 2022
        quote: > 
          Koç University is a non-profit private university in Istanbul, Turkey. 
          Founded in 1993, Koç University is one of the most prestigious universities in Turkey.
        description: | # this will include new lines to allow paragraphs
          My studies in Electrical & Electronics Engineering (EEE) focused mostly on signal processing, 
          machine learning, artificial intelligence and information theory. After completing several
          specialization courses with merit, I was awarded with track certificate of 
          <mark>artificial intelligence</mark>. My thesis project at EEE department was awarded with the
          second place after working under supervision of Professor Murat Tekalp.
      - layout: left
        title: Koç University
        sub_title: BA Economics (Double Major)
        caption: 2017 - 2022
        description: | # this will include new lines to allow paragraphs
          Having a keen interest in complex networks and game theory, I pursue a double major in Economics.
          The specialization courses I have taken focused on <mark>financial markets</mark>, 
          <mark>game theory</mark> and <mark>information & contract theory</mark>. I achieved
          my track certificate in <mark>financial engineering</mark> after completing required courses in
          the program.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my free time, I enjoy playing <mark>pool</mark>, <mark>piano</mark> and <mark>chess</mark>.
      Feel free to contact me for a good game of pool or chess if proximity is not a problem.
      <br>
      <br>
      <br>
      <br>
      > *“The learned man knows that he is ignorant.”* ― *Victor Hugo*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
